### ISSUE TITLE
Injection kinda bad

### ISSUE THREAD

**Issue by frontwarerbx** [BitdancerStudios/KrampUI#1]
When I inject KrampUI and join a game the execute button shows up, but when I change games, that button gets grayed out and doesn't come back.

**Comment by cuddlingintokyo** [comment]
the same happens with the loader if you use an auto inject without waiting for the game to load properly, 
tldr: don't use auto inject.

**Comment by Pixeluted** [comment]
Hello,

This happens because of krampus auto execution failing on rejoin, currently WebUI is not working so KrampUI is setting up its own websocket server and making krampus connect to that websocket,

Unfortunately we cannot do anything to make it more reliable, we are waiting for krampus developers to add local websocket which would be more reliable.

**Comment by Pixeluted** [comment]
Issue will be fixed one krampus add local websocket
